DROP DATABASE IF EXISTS drello_dev;
CREATE DATABASE drello_dev;
USE drello_dev;

CREATE TABLE users(
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT INTO users (username, password) VALUES('root', '$2b$10$EXwMSYQmQNtCdF8Dh.BA.eio2fgCByAaxFHDxqWIqaMkHArh3iT7y');

CREATE TABLE boards(
	id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    
    name VARCHAR(255),
    color VARCHAR(255),
    image_url VARCHAR(255),
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (user_id) REFERENCES users(id)
);
INSERT INTO boards (user_id, name, color) VALUES(1, 'board 1', 'black');


CREATE TABLE lists(
	id INT AUTO_INCREMENT PRIMARY KEY,
    board_id INT NOT NULL,
    
    name VARCHAR(255),
    position INT NOT NULL,
    color VARCHAR(255),
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (board_id) REFERENCES boards(id)
);
INSERT INTO lists(board_id, name, position, color) VALUES(1, 'list 1', 0, 'black');


CREATE TABLE cards(
	id INT AUTO_INCREMENT PRIMARY KEY,
    list_id INT NOT NULL,
    
    name VARCHAR(255),
    position INT NOT NULL,
    color VARCHAR(255),
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (list_id) REFERENCES lists(id)
);